name: Gitea Actions Java Build
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v3
      - uses: https://github.com/actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '20'

      - name: build dependencies
        run: scripts/build.sh a
      - uses: https://gitea.com/actions/release-action@main
        with:
          files: |-
            target/*.jar
            target/buid/*.run
          api_key: '${{secrets.RELEASE_TOKEN}}'
