name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: https://github.com/actions/checkout@v3
      - name: install dependencies
        run: |
          apt-get update
          apt-get install -y curl zip unzip
          curl -s "https://get.sdkman.io" | bash
      - name: prepare java build env
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk update
          sdk env install
          sdk env use
          chmod +x scripts/build.sh
          scripts/build.sh a
          